#! /bin/sh
#
# rebuild: rebuild Makefile.in, configure, etc. using GNU automake, autoconf,
# and libtool.
#
# $Id: rebuild,v 1.2 1999/09/08 19:40:59 erikm Exp $
#

echo '$Id: rebuild,v 1.2 1999/09/08 19:40:59 erikm Exp $'
echo "Setting up for use with system supplied compilers"
echo ""

echo "Running automake ... "
automake --add-missing --gnu --include-deps

echo "Running aclocal ... "
aclocal

echo "Running autoconf ... "
autoconf

echo "Running autoheader ... "
autoheader
